In [2]:

import spacy
import pandas as pd

In [3]:
# $ python -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm");

In [4]:
# our text is from jane austin's 'emma'
# we have removed punctuation, lowercased but left in stop words
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [10]:
# create a spacy doc from our text - this will generate tokens and their assosciated pos tags
spacy_doc = nlp(emma_ja)
for token in spacy_doc:
    print(token.text, token.pos_)

emma PROPN
woodhouse PROPN
handsome ADJ
clever ADJ
and CCONJ
rich ADJ
with ADP
a DET
comfortable ADJ
home NOUN
and CCONJ
happy ADJ
disposition NOUN
seemed VERB
to PART
unite VERB
some PRON
of ADP
the DET
best ADJ
blessings NOUN
of ADP
existence NOUN
and CCONJ
had AUX
lived VERB
nearly ADV
twentyone NUM
years NOUN
in ADP
the DET
world NOUN
with ADP
very ADV
little ADJ
to PART
distress NOUN
or CCONJ
vex NOUN
her PRON
she PRON
was AUX
the DET
youngest ADJ
of ADP
the DET
two NUM
daughters NOUN
of ADP
a DET
most ADV
affectionate ADJ
indulgent ADJ
father NOUN
and CCONJ
had AUX
in ADP
consequence NOUN
of ADP
her PRON
sisters NOUN
marriage NOUN
been AUX
mistress NOUN
of ADP
his PRON
house NOUN
from ADP
a DET
very ADV
early ADJ
period NOUN
her PRON
mother NOUN
had AUX
died VERB
too ADV
long ADV
ago ADV
for SCONJ
her PRON
to PART
have VERB
more ADJ
than ADP
an DET
indistinct ADJ
remembrance NOUN
of ADP
her PRON
caresses NOUN
and CCONJ
her PRON
place NOUN
had AUX
been AUX
supplied VERB
by ADP
an DET
excellent ADJ
woman NOUN
as ADP
governess NOUN
who PRON
had AUX
fallen VERB
little ADJ
short ADJ
of ADP
a DET
mother NOUN
in ADP
affection NOUN
sixteen NUM
years NOUN
had AUX
miss PROPN
taylor PROPN
been AUX
in ADP
mr PROPN
woodhouses PROPN
family NOUN
less ADV
as ADP
a DET
governess NOUN
than ADP
a DET
friend NOUN
very ADV
fond ADJ
of ADP
both DET
daughters NOUN
but CCONJ
particularly ADV
of ADP
emma NOUN
between ADP
them PRON
it PRON
was AUX
more ADV
the DET
intimacy NOUN
of ADP
sisters NOUN
even ADV
before SCONJ
miss PROPN
taylor PROPN
had AUX
ceased VERB
to PART
hold VERB
the DET
nominal ADJ
office NOUN
of ADP
governess NOUN
the DET
mildness NOUN
of ADP
her PRON
temper NOUN
had AUX
hardly ADV
allowed VERB
her PRON
to PART
impose VERB
any DET
restraint NOUN
and CCONJ
the DET
shadow NOUN
of ADP
authority NOUN
being AUX
now ADV
long ADV
passed VERB
away ADV
they PRON
had AUX
been AUX
living VERB
together ADV
as SCONJ
friend NOUN
and CCONJ
friend NOUN
very ADV
mutually ADV
attached VERB
and CCONJ
emma NOUN
doing VERB
just ADV
what PRON
she PRON
liked VERB
highly ADV
esteeming VERB
miss VERB
taylors NOUN
judgment NOUN
but CCONJ
directed VERB
chiefly ADV
by ADP
her PRON
own ADJ

In [11]:
# extract the tokens and pos tags into a dataframe
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])

In [16]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token': token.text, 'pos_tag': token.pos_}])], ignore_index=True)

In [24]:
# print(pos_df.head(10).to_string(index=False))
pos_df.head(10)

         token pos_tag
0         emma   PROPN
1    woodhouse   PROPN
2     handsome     ADJ
3       clever     ADJ
4          and   CCONJ
5         rich     ADJ
6         with     ADP
7            a     DET
8  comfortable     ADJ
9         home    NOUN

In [33]:
# token frequency count
pos_df_counts = pos_df \
    .groupby(['token','pos_tag']) \
    .size() \
    .reset_index(name='count') \
    .sort_values(['count'], ascending=False)
pos_df_counts.head(10)

    token pos_tag  count
88     of     ADP     28
54    her    PRON     18
49    had     AUX     18
6     and   CCONJ     16
111   the     DET     16
0       a     DET     12
114    to    PART     10
61     in     ADP      8
120  very     ADV      8
13   been     AUX      8

In [55]:
# → “How many total tokens were tagged as NOUN?”
# # counts of pos_tags
# pos_df_postags = pos_df \
#     .groupby(['pos_tag']) \
#     .size() \
#     .reset_index(name='count') \
#     .sort_values(['count'], ascending=False)
# pos_df_postags.head(10)

# → “How many distinct tokens were tagged as NOUN?”
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)
pos_df_poscounts.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [59]:
# see most common nouns
nouns = pos_df_counts[pos_df_counts['pos_tag'] == 'NOUN'][0:10]
nouns

         token pos_tag  count
48   governess    NOUN      6
46      friend    NOUN      6
130      years    NOUN      4
28   daughters    NOUN      4
35        emma    NOUN      4
82      mother    NOUN      4
103    sisters    NOUN      4
1    affection    NOUN      2
11   authority    NOUN      2
32    distress    NOUN      2

In [60]:
# see most common verbs
verbs = pos_df_counts[pos_df_counts['pos_tag'] == 'VERB'][0:10]
verbs

        token pos_tag  count
33      doing    VERB      2
29       died    VERB      2
37  esteeming    VERB      2
41     fallen    VERB      2
23     ceased    VERB      2
30   directed    VERB      2
10   attached    VERB      2
4     allowed    VERB      2
60     impose    VERB      2
57       hold    VERB      2